# spec/.rubocop.yml

require: rubocop-rails

inherit_from:
  - ../.rubocop.yml

StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - './*_helper.rb'

# describe block
Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  